Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    ordered_features: null
    feature_specs: null

DIEN_test:
    model: DIEN
    dataset_id: tiny_seq
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    dnn_hidden_units: [64, 32]
    dnn_activations: Dice
    net_dropout: 0
    dien_target_field: adgroup_id
    dien_sequence_field: click_sequence
    dien_neg_seq_field: []
    gru_type: AUGRU
    attention_type: bilinear_attention
    attention_hidden_units: [80, 40]
    attention_activation: "Sigmoid"
    attention_dropout: 0
    use_attention_softmax: True
    aux_hidden_units: [100, 50]
    aux_activation: "Sigmoid"
    aux_loss_alpha: 0
    batch_norm: True
    epochs: 1
    shuffle: True
    seed: 20222023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

DIEN_default: # This is a config template
    model: DIEN
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: Dice
    net_dropout: 0
    dien_target_field: adgroup_id
    dien_sequence_field: click_sequence
    dien_neg_seq_field: []
    gru_type: AUGRU
    attention_type: bilinear_attention
    attention_hidden_units: [80, 40]
    attention_activation: "Sigmoid"
    attention_dropout: 0
    use_attention_softmax: True
    aux_hidden_units: [100, 50]
    aux_activation: "Sigmoid"
    aux_loss_alpha: 0
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 20222023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'