Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    ordered_features: null
    feature_specs: null

FGCNN_test:
    model: FGCNN
    dataset_id: tiny_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-8
    net_regularizer: 0
    net_dropout: 0
    batch_size: 128
    embedding_dim: 4
    share_embedding: False
    channels: [14, 16, 18, 20]
    kernel_heights: [7, 7, 7, 7]
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    conv_activation: Tanh
    conv_batch_norm: True
    dnn_hidden_units: [64, 64, 64]
    dnn_activations: ReLU
    dnn_batch_norm: False
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

FGCNN_default: # This is a config template
    model: FGCNN
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    net_dropout: 0
    batch_size: 10000
    embedding_dim: 20
    share_embedding: False
    channels: [38, 40, 42, 44]
    kernel_heights: [9, 9, 9, 9]
    pooling_sizes: [2, 2, 2, 2]
    recombined_channels: [3, 3, 3, 3]
    conv_activation: Tanh
    conv_batch_norm: True
    dnn_hidden_units: [4096, 2048]
    dnn_activations: ReLU
    dnn_batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
