Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    ordered_features: null
    feature_specs: null

ONN_test:
    model: ONN
    dataset_id: tiny_h5
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-8
    net_regularizer: 0
    hidden_units: [64, 32]
    hidden_activations: relu
    net_dropout: 0
    batch_norm: False
    batch_size: 128
    embedding_dim: 4
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

ONN_default: # This is a config template
    model: ONN
    dataset_id: TBD
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    hidden_units: [64, 64, 64]
    hidden_activations: relu
    net_dropout: 0
    batch_norm: False
    batch_size: 10000
    embedding_dim: 2
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

ONNv2_test:
    model: ONNv2
    dataset_id: tiny_h5
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    hidden_units: [64, 32]
    hidden_activations: relu
    net_dropout: 0
    batch_norm: False
    batch_size: 128
    embedding_dim: 2
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

ONNv2_default: # This is a config template
    model: ONNv2
    dataset_id: TBD
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    hidden_units: [64, 64, 64]
    hidden_activations: relu
    net_dropout: 0
    batch_norm: False
    batch_size: 10000
    embedding_dim: 2
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
