Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    ordered_features: null
    feature_specs: null

BST_test:
    model: BST
    dataset_id: tiny_seq
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    num_heads: 4
    stacked_transformer_layers: 1
    attention_dropout: 0
    net_dropout: 0
    layer_norm: True
    use_residual: True
    bst_target_field: adgroup_id
    bst_sequence_field: click_sequence
    seq_pooling_type: mean
    use_position_emb: True
    use_causal_mask: False
    batch_norm: False
    epochs: 1
    shuffle: True
    seed: 20222023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

BST_default: # This is a config template
    model: BST
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 16
    dnn_hidden_units: [1024, 512, 256]
    dnn_activations: relu
    num_heads: 4
    stacked_transformer_layers: 1
    attention_dropout: 0
    net_dropout: 0
    layer_norm: True
    use_residual: True
    bst_target_field: adgroup_id
    bst_sequence_field: click_sequence
    seq_pooling_type: mean
    use_position_emb: True
    use_causal_mask: False
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 20222023
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

