### Tiny data for tests only
tiny_tfrecord:
    data_root: ../../../data/
    data_format: tfrecord
    train_data: ../../../data/tiny_tfrecord/train.tfrecord
    valid_data: ../../../data/tiny_tfrecord/valid.tfrecord
    test_data: ../../../data/tiny_tfrecord/test.tfrecord

