### Tiny data for tests only
tiny_h5:
    data_root: ../../../data/
    data_format: h5
    train_data: ../../../data/tiny_h5/train.h5
    valid_data: ../../../data/tiny_h5/valid.h5
    test_data: ../../../data/tiny_h5/test.h5

tiny_csv:
    data_root: ../../../data/
    data_format: csv
    train_data: ../../../data/tiny_csv/train_sample.csv
    valid_data: ../../../data/tiny_csv/valid_sample.csv
    test_data: ../../../data/tiny_csv/test_sample.csv
    min_categr_count: 1
    feature_cols:
        [{name: ["userid","adgroup_id","pid","cate_id","campaign_id","customer","brand","cms_segid",
                 "cms_group_id","final_gender_code","age_level","pvalue_level","shopping_level","occupation"], 
                 active: True, dtype: str, type: categorical}]
    label_col: {name: clk, dtype: float}
