Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    ordered_features: null
    feature_specs: null

DIN_test:
    model: DIN
    dataset_id: tiny_seq
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    attention_hidden_units: [64]
    attention_hidden_activations: "Dice"
    attention_output_activation: null
    attention_dropout: 0
    din_target_field: adgroup_id
    din_sequence_field: click_sequence
    net_dropout: 0
    batch_norm: False
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

DIN_test2:
    model: DIN
    dataset_id: tiny_seq2
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    attention_hidden_units: [64]
    attention_hidden_activations: "Dice"
    attention_output_activation: null
    attention_dropout: 0
    din_target_field: adgroup_id
    din_sequence_field: click_sequence
    net_dropout: 0
    batch_norm: False
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'

DIN_default: # This is a config template
    model: DIN
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 40
    dnn_hidden_units: [500, 500, 500]
    dnn_activations: relu
    attention_hidden_units: [64]
    attention_hidden_activations: "Dice"
    attention_output_activation: null
    attention_dropout: 0
    din_target_field: item_id
    din_sequence_field: click_history
    din_use_softmax: False
    net_dropout: 0
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

