Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    ordered_features: null
    feature_specs: null

DESTINE_test:
    model: DESTINE
    dataset_id: tiny_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    attention_dim: 4
    num_heads: 2
    attention_layers: 2
    dnn_hidden_units: [64, 32]
    dnn_activations: relu
    att_dropout: 0
    net_dropout: 0
    relu_before_att: False
    use_scale: True
    use_wide: False
    residual_mode: "each_layer"
    batch_norm: True
    epochs: 1
    shuffle: True
    seed: 2021
    monitor: 'AUC'
    monitor_mode: 'max'

DESTINE_default: # This is a config template
    model: DESTINE
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 40
    attention_dim: 40
    num_heads: 2
    attention_layers: 2
    dnn_hidden_units: [400, 400, 400]
    dnn_activations: relu
    att_dropout: 0
    net_dropout: 0
    relu_before_att: False
    use_scale: True
    use_wide: False
    residual_mode: "each_layer"
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2021
    monitor: 'AUC'
    monitor_mode: 'max'

