Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    ordered_features: null
    feature_specs: null

SAM_test:
    model: SAM
    dataset_id: tiny_h5
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    interaction_type: "SAM2E"
    aggregation: "concat"
    num_interaction_layers: 2
    use_residual: False
    net_dropout: 0
    epochs: 1
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'

SAM_default: # This is a config template
    model: SAM
    dataset_id: TBD
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 0
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 40
    interaction_type: "SAM2E"
    aggregation: "concat"
    num_interaction_layers: 3
    use_residual: False
    net_dropout: 0
    epochs: 100
    shuffle: True
    seed: 2022
    monitor: 'AUC'
    monitor_mode: 'max'